FROM python:3.9.13

COPY /app_GL /app
WORKDIR /app
RUN apt-get update
RUN pip install --upgrade pip
RUN pip install pyopenssl==22.0.0
RUN pip install "python-jose[cryptography]"
RUN pip install "passlib[bcrypt]"
RUN pip install --no-cache-dir -r requirements.txt
CMD python3 main.py
